services:
  app:
    build:
      context: .
      dockerfile: src/ZiziBot.Engine/Dockerfile
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017