version: "3"
services:
  dotnet-container:
    image: mcr.microsoft.com/devcontainers/dotnet:8.0
    command: sleep infinity

  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    expose:
      - 27017